"""Public type information for the jseries Python package."""

from os import PathLike
from typing import Sequence, overload

__version__: str

class JSeriesError(Exception): ...
class SchemaError(JSeriesError): ...
class DecodeError(JSeriesError): ...

class DecodedField:
    @property
    def id(self) -> str: ...
    @property
    def definition_ref(self) -> str: ...
    @property
    def word(self) -> int: ...
    @property
    def lsb(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def raw(self) -> int: ...
    @property
    def status(self) -> str: ...
    @property
    def unsigned_value(self) -> int | None: ...
    @property
    def signed_value(self) -> int | None: ...
    @property
    def numerator(self) -> int | None: ...
    @property
    def denominator(self) -> int | None: ...
    @property
    def unit(self) -> str | None: ...
    @property
    def label(self) -> str | None: ...
    @property
    def selector(self) -> str | None: ...
    @property
    def error(self) -> str | None: ...

class DecodedRecord:
    @property
    def package_id(self) -> str: ...
    @property
    def package_version(self) -> str: ...
    @property
    def qualification(self) -> str: ...
    @property
    def source_id(self) -> str: ...
    @property
    def source_offset(self) -> int: ...
    @property
    def message_id(self) -> str: ...
    @property
    def fields(self) -> list[DecodedField]: ...

class Decoder:
    def __init__(self, schema_path: str | PathLike[str]) -> None: ...
    def message_ids(self) -> list[str]: ...
    @overload
    def decode(
        self,
        message_id: str,
        values: Sequence[int],
        *,
        source_id: str | None = None,
        source_offset: int = 0,
    ) -> DecodedRecord: ...
    @overload
    def decode(
        self,
        message_id: str,
        values: Sequence[Sequence[int]],
        *,
        source_id: str | None = None,
        source_offset: int = 0,
    ) -> list[DecodedRecord]: ...
