[package]
name = "jseries-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
rand.workspace = true
trybuild.workspace = true

[[bench]]
name = "decode"
harness = false

[lints]
workspace = true
