// Generated by tools/schema_compile.py. DO NOT EDIT.
// SYNTHETIC ONLY: no authoritative message definitions are present.
use crate::{Baseline, schema::{Bundle, Condition, FieldSpec, Interpretation, MessageSpec, SchemaKind}};

pub static BUNDLE_D: Bundle = Bundle {
    baseline: Baseline::D,
    schema_id: "synthetic-D-0.1.0",
    schema_version: "0.1.0",
    profile_id: "synthetic-fixture-only",
    digest_sha256: "ad3451ab85e3eb71e24b016eae4351a14c591d706744438b6d3689ca6caa7e54",
    kind: SchemaKind::Synthetic,
    messages: &[
        MessageSpec {
            id: "SYNTH-01",
            word_bits: 16,
            fields: &[
                FieldSpec {
                    id: "mode",
                    definition_ref: "SYNTH:MODE",
                    lsb: 0, width: 2,
                    interpretation: Interpretation::Enumeration(&[(0u128, "idle"), (1u128, "active")]),
                    specials: &[(3u128, "not_reported")],
                    condition: None,
                },
                FieldSpec {
                    id: "level",
                    definition_ref: "SYNTH:LEVEL",
                    lsb: 2, width: 6,
                    interpretation: Interpretation::ScaledUnsigned { numerator: 1i64, denominator: 1u64, unit: "test_units" },
                    specials: &[(63u128, "no_statement")],
                    condition: None,
                },
                FieldSpec {
                    id: "auxiliary",
                    definition_ref: "SYNTH:AUXILIARY",
                    lsb: 8, width: 4,
                    interpretation: Interpretation::Unsigned,
                    specials: &[(15u128, "unknown")],
                    condition: Some(Condition { selector: "mode", equals: 1u128 }),
                },
                FieldSpec {
                    id: "flags",
                    definition_ref: "SYNTH:FLAGS",
                    lsb: 12, width: 4,
                    interpretation: Interpretation::Enumeration(&[(0u128, "none"), (1u128, "set")]),
                    specials: &[],
                    condition: None,
                },
            ],
        },
    ],
};

pub static BUNDLE_E: Bundle = Bundle {
    baseline: Baseline::E,
    schema_id: "synthetic-E-0.1.0",
    schema_version: "0.1.0",
    profile_id: "synthetic-fixture-only",
    digest_sha256: "37bf2f13b97acdc16ef7cd5e68113399c75c5727bfc1361b27376cc9ebdc8f7c",
    kind: SchemaKind::Synthetic,
    messages: &[
        MessageSpec {
            id: "SYNTH-01",
            word_bits: 16,
            fields: &[
                FieldSpec {
                    id: "mode",
                    definition_ref: "SYNTH:MODE",
                    lsb: 0, width: 2,
                    interpretation: Interpretation::Enumeration(&[(0u128, "idle"), (1u128, "active")]),
                    specials: &[(3u128, "not_reported")],
                    condition: None,
                },
                FieldSpec {
                    id: "level",
                    definition_ref: "SYNTH:LEVEL",
                    lsb: 2, width: 6,
                    interpretation: Interpretation::ScaledUnsigned { numerator: 2i64, denominator: 1u64, unit: "test_units" },
                    specials: &[(63u128, "no_statement")],
                    condition: None,
                },
                FieldSpec {
                    id: "auxiliary",
                    definition_ref: "SYNTH:AUXILIARY",
                    lsb: 8, width: 4,
                    interpretation: Interpretation::Unsigned,
                    specials: &[(15u128, "unknown")],
                    condition: Some(Condition { selector: "mode", equals: 1u128 }),
                },
                FieldSpec {
                    id: "flags",
                    definition_ref: "SYNTH:FLAGS",
                    lsb: 12, width: 4,
                    interpretation: Interpretation::Enumeration(&[(0u128, "none"), (1u128, "set")]),
                    specials: &[],
                    condition: None,
                },
            ],
        },
    ],
};

pub static BUNDLE_F: Bundle = Bundle {
    baseline: Baseline::F,
    schema_id: "synthetic-F-0.1.0",
    schema_version: "0.1.0",
    profile_id: "synthetic-fixture-only",
    digest_sha256: "bfc3a2678b1b87d91c62662cf104ad9a4403170f902d160475e36a950d1d893a",
    kind: SchemaKind::Synthetic,
    messages: &[
        MessageSpec {
            id: "SYNTH-01",
            word_bits: 16,
            fields: &[
                FieldSpec {
                    id: "mode",
                    definition_ref: "SYNTH:MODE",
                    lsb: 0, width: 2,
                    interpretation: Interpretation::Enumeration(&[(0u128, "idle"), (1u128, "active")]),
                    specials: &[(3u128, "not_reported")],
                    condition: None,
                },
                FieldSpec {
                    id: "level",
                    definition_ref: "SYNTH:LEVEL",
                    lsb: 2, width: 6,
                    interpretation: Interpretation::ScaledUnsigned { numerator: 3i64, denominator: 1u64, unit: "test_units" },
                    specials: &[(63u128, "no_statement")],
                    condition: None,
                },
                FieldSpec {
                    id: "auxiliary",
                    definition_ref: "SYNTH:AUXILIARY",
                    lsb: 8, width: 4,
                    interpretation: Interpretation::Unsigned,
                    specials: &[(15u128, "unknown")],
                    condition: Some(Condition { selector: "mode", equals: 1u128 }),
                },
                FieldSpec {
                    id: "flags",
                    definition_ref: "SYNTH:FLAGS",
                    lsb: 12, width: 4,
                    interpretation: Interpretation::Enumeration(&[(0u128, "none"), (1u128, "set")]),
                    specials: &[],
                    condition: None,
                },
            ],
        },
    ],
};

pub static BUNDLE_F_C1: Bundle = Bundle {
    baseline: Baseline::FChange1,
    schema_id: "synthetic-F-C1-0.1.0",
    schema_version: "0.1.0",
    profile_id: "synthetic-fixture-only",
    digest_sha256: "4ae7c57d2ae6bfa68d28a435e6b139b480ae0694d79fb29458f46e8714dd9ce9",
    kind: SchemaKind::Synthetic,
    messages: &[
        MessageSpec {
            id: "SYNTH-01",
            word_bits: 16,
            fields: &[
                FieldSpec {
                    id: "mode",
                    definition_ref: "SYNTH:MODE",
                    lsb: 0, width: 2,
                    interpretation: Interpretation::Enumeration(&[(0u128, "idle"), (1u128, "active")]),
                    specials: &[(3u128, "not_reported")],
                    condition: None,
                },
                FieldSpec {
                    id: "level",
                    definition_ref: "SYNTH:LEVEL",
                    lsb: 2, width: 6,
                    interpretation: Interpretation::ScaledUnsigned { numerator: 4i64, denominator: 1u64, unit: "test_units" },
                    specials: &[(63u128, "no_statement")],
                    condition: None,
                },
                FieldSpec {
                    id: "auxiliary",
                    definition_ref: "SYNTH:AUXILIARY",
                    lsb: 8, width: 4,
                    interpretation: Interpretation::Unsigned,
                    specials: &[(15u128, "unknown")],
                    condition: Some(Condition { selector: "mode", equals: 1u128 }),
                },
                FieldSpec {
                    id: "flags",
                    definition_ref: "SYNTH:FLAGS",
                    lsb: 12, width: 4,
                    interpretation: Interpretation::Enumeration(&[(0u128, "none"), (1u128, "set")]),
                    specials: &[],
                    condition: None,
                },
            ],
        },
    ],
};

pub static BUNDLE_G: Bundle = Bundle {
    baseline: Baseline::G,
    schema_id: "synthetic-G-0.1.0",
    schema_version: "0.1.0",
    profile_id: "synthetic-fixture-only",
    digest_sha256: "5624583e9729a08b9cf0154d9709dd6e367ee5ec82a24111f0d6b6205bf50a6f",
    kind: SchemaKind::Synthetic,
    messages: &[
        MessageSpec {
            id: "SYNTH-01",
            word_bits: 16,
            fields: &[
                FieldSpec {
                    id: "mode",
                    definition_ref: "SYNTH:MODE",
                    lsb: 0, width: 2,
                    interpretation: Interpretation::Enumeration(&[(0u128, "idle"), (1u128, "active")]),
                    specials: &[(3u128, "not_reported")],
                    condition: None,
                },
                FieldSpec {
                    id: "level",
                    definition_ref: "SYNTH:LEVEL",
                    lsb: 2, width: 6,
                    interpretation: Interpretation::ScaledUnsigned { numerator: 5i64, denominator: 1u64, unit: "test_units" },
                    specials: &[(63u128, "no_statement")],
                    condition: None,
                },
                FieldSpec {
                    id: "auxiliary",
                    definition_ref: "SYNTH:AUXILIARY",
                    lsb: 8, width: 4,
                    interpretation: Interpretation::Unsigned,
                    specials: &[(15u128, "unknown")],
                    condition: Some(Condition { selector: "mode", equals: 1u128 }),
                },
                FieldSpec {
                    id: "flags",
                    definition_ref: "SYNTH:FLAGS",
                    lsb: 12, width: 4,
                    interpretation: Interpretation::Enumeration(&[(0u128, "none"), (1u128, "set")]),
                    specials: &[],
                    condition: None,
                },
            ],
        },
    ],
};

pub static BUNDLE_H: Bundle = Bundle {
    baseline: Baseline::H,
    schema_id: "synthetic-H-0.1.0",
    schema_version: "0.1.0",
    profile_id: "synthetic-fixture-only",
    digest_sha256: "db5273bfee3df079f299d97102ec55ed88b3da2ee008572029e83cc22c1445ab",
    kind: SchemaKind::Synthetic,
    messages: &[
        MessageSpec {
            id: "SYNTH-01",
            word_bits: 16,
            fields: &[
                FieldSpec {
                    id: "mode",
                    definition_ref: "SYNTH:MODE",
                    lsb: 0, width: 2,
                    interpretation: Interpretation::Enumeration(&[(0u128, "idle"), (1u128, "active")]),
                    specials: &[(3u128, "not_reported")],
                    condition: None,
                },
                FieldSpec {
                    id: "level",
                    definition_ref: "SYNTH:LEVEL",
                    lsb: 2, width: 6,
                    interpretation: Interpretation::ScaledUnsigned { numerator: 10i64, denominator: 1u64, unit: "test_units" },
                    specials: &[(63u128, "no_statement")],
                    condition: None,
                },
                FieldSpec {
                    id: "auxiliary",
                    definition_ref: "SYNTH:AUXILIARY",
                    lsb: 8, width: 4,
                    interpretation: Interpretation::Unsigned,
                    specials: &[(15u128, "unknown")],
                    condition: Some(Condition { selector: "mode", equals: 1u128 }),
                },
                FieldSpec {
                    id: "flags",
                    definition_ref: "SYNTH:FLAGS",
                    lsb: 12, width: 4,
                    interpretation: Interpretation::Enumeration(&[(0u128, "none"), (1u128, "set")]),
                    specials: &[],
                    condition: None,
                },
            ],
        },
        MessageSpec {
            id: "SYNTH-H-ONLY",
            word_bits: 8,
            fields: &[
                FieldSpec {
                    id: "counter",
                    definition_ref: "SYNTH:COUNTER",
                    lsb: 0, width: 8,
                    interpretation: Interpretation::Unsigned,
                    specials: &[],
                    condition: None,
                },
            ],
        },
    ],
};
